---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: "tests/fixture/readonly_file.txt"
    -   id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format
        exclude: ".json"
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        language: system
        entry: clang-tidy -p build/compile_commands.json -extra-arg=-std=c++20
        files: cpp
        exclude: "^build/"
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
      - id: cmakelint
  - repo: https://github.com/sco1/brie-commit
    rev: v1.1.0
    hooks:
    -   id: brie-commit
