---
exclude: ^include
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
        additional_dependencies: [ ruamel.yaml>=0.15 ]
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: "tests/fixture/no_newline_file.txt"
    -   id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        exclude: ".json"
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
      - id: cmakelint
        exclude: "^include/"
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    -   id: reorder-python-imports
        args: [--py310-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    - id: add-trailing-comma
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
    - id: actionlint
  - repo: https://github.com/sco1/brie-commit
    rev: v1.1.0
    hooks:
    -   id: brie-commit
