# This code was disabled with the 0.0.3 release as builds were failing
# due to retrieving the rawterm version in github actions
# <https://github.com/Ttibsi/iris/actions/runs/23191859408/job/67389782020>
# The root cause is that github actions will require extra muddling around
# with checkout and secrets to be able to read a separate repo. I've disabled
# this for now as I don't want to mirror code from run.py in GHA yaml.
# However I may come back to this for a future release.


name: build-artifact
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      slug:
        required: true
        type: string

jobs:
  build:
    if: false
    permissions:
      contents: write
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: sudo apt-get install llvm-18 libstdc++-14-dev git
      - run: ./run.py --release
      - run: mv release iris-${{ github.ref_name }}-${{ inputs.slug }}
      - run: tar czf iris-${{ github.ref_name }}-${{ inputs.slug }}.tar iris-${{ github.ref_name }}-${{ inputs.slug }}
      - name: Upload Release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: iris-${{ github.ref_name }}-${{ inputs.slug }}.tar
          asset_name: iris-${{ github.ref_name }}-${{ inputs.slug }}.tar
