name: make-release
on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build_linux_x86:
    permissions:
      contents: write
    uses: ./.github/workflows/build_artifact.yml
    with:
      runner: ubuntu-24.04
      slug: x86_64

  build_linux_arm:
    permissions:
      contents: write
    uses: ./.github/workflows/build_artifact.yml
    with:
      runner: ubuntu-24.04-arm
      slug: arm64
